name: Chocolatine
on:
  push:
    branches-ignore:
      - 'ga-ignore/*'
  pull_request:
    branches-ignore:
      - 'ga-ignore/*'

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: check coding-style
        run: check.sh . .

  check_program_compilation:
    needs: [check_coding_style]
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: check program build
        run: make && make re 
        timeout-minutes: 2
      - name: check clean
        run: make clean

  run_tests:
    needs: [check_coding_style, check_program_compilation]
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
      - name: launch make tests_run 
        run: make tests_run 
        timeout-minutes: 2

  push_to_mirror:
    needs: [check_program_compilation, run_tests] 
    runs-on: ubuntu-latest
    steps:                                              
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ secrets.MIRROR_URL }}
          ssh_private_key:                              
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
